# Generated by Django 5.2.9 on 2026-01-07 05:48

import cryptography.fernet
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='encryption_key',
            field=models.BinaryField(default=cryptography.fernet.Fernet.generate_key),
        ),
    ]
